//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class QBANKEntities : DbContext
{
    public QBANKEntities()
        : base("name=QBANKEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<FIB> FIBs { get; set; }
    public virtual DbSet<MCQopt> MCQopts { get; set; }
    public virtual DbSet<Question> Questions { get; set; }
}
