//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FIB
{
    public int id { get; set; }
    public int Fid { get; set; }
    public string Answer { get; set; }

    public virtual Question Question { get; set; }
}

public partial class MCQopt
{
    public int id { get; set; }
    public int Oid { get; set; }
    public string opt { get; set; }
    public Nullable<bool> correct { get; set; }

    public virtual Question Question { get; set; }
}

public partial class Question
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Question()
    {
        this.FIBs = new HashSet<FIB>();
        this.MCQopts = new HashSet<MCQopt>();
    }

    public int id { get; set; }
    public string ques { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FIB> FIBs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MCQopt> MCQopts { get; set; }
}
